var raids = [
  {
    "Tier": 1,
    "idRaid": 129,
    "RaidBoss": "Magikarp",
    "BossCP": 1165,
    "Min CP": 104,
    "MaxCP": 125,
    "pokeAtac1": "Jolteon",
    "quick1": "Impactrueno",
    "charge1": "Rayo",
    "pokeAtac2": "Magneton",
    "quick2": "Chispa",
    "charge2": "Electrocañón",
    "pokeAtac3": "Raichu",
    "quick3": "Chispa",
    "charge3": "Voltio Cruel"
  },
  {
    "Tier": 1,
    "idRaid": 153,
    "RaidBoss": "Bayleef",
    "BossCP": 4375,
    "Min CP": 689,
    "MaxCP": 740,
    "pokeAtac1": "Flareon",
    "quick1": "Giro Fuego",
    "charge1": "Sofoco",
    "pokeAtac2": "Arcanine",
    "quick2": "Colmillo Ígneo",
    "charge2": "Llamarada",
    "pokeAtac3": "Charizard",
    "quick3": "Giro Fuego",
    "charge3": "Sofoco"
  },
  {
    "Tier": 1,
    "idRaid": 156,
    "RaidBoss": "Quilava",
    "BossCP": 5085,
    "Min CP": 793,
    "MaxCP": 847,
    "pokeAtac1": "Rhydon",
    "quick1": "Bofetón Lodo",
    "charge1": "Terremoto",
    "pokeAtac2": "Golem",
    "quick2": "Lanzarrocas",
    "charge2": "Roca Afilada",
    "pokeAtac3": "Donphan",
    "quick3": "Contraataque",
    "charge3": "Terremoto"
  },
  {
    "Tier": 1,
    "idRaid": 159,
    "RaidBoss": "Croconaw",
    "BossCP": 5207,
    "Min CP": 857,
    "MaxCP": 913,
    "pokeAtac1": "Jolteon",
    "quick1": "Impactrueno",
    "charge1": "Rayo",
    "pokeAtac2": "Magneton",
    "quick2": "Chispa",
    "charge2": "Electrocañón",
    "pokeAtac3": "Raichu",
    "quick3": "Chispa",
    "charge3": "Voltio Cruel"
  },
  {
    "Tier": 2,
    "idRaid": 89,
    "RaidBoss": "Muk",
    "BossCP": 12269,
    "Min CP": 1474,
    "MaxCP": 1548,
    "pokeAtac1": "Rhydon",
    "quick1": "Bofetón Lodo",
    "charge1": "Terremoto",
    "pokeAtac2": "Golem",
    "quick2": "Lanzarrocas",
    "charge2": "Roca Afilada",
    "pokeAtac3": "Alakazam",
    "quick3": "Confusión",
    "charge3": "Premonición"
  },
  {
    "Tier": 2,
    "idRaid": 103,
    "RaidBoss": "Exeggutor",
    "BossCP": 13839,
    "Min CP": 1589,
    "MaxCP": 1666,
    "pokeAtac1": "Scizor",
    "quick1": "Puño Bala",
    "charge1": "Cabeza de Hierro",
    "pokeAtac2": "Pinsir",
    "quick2": "Picadura",
    "charge2": "Tijera X",
    "pokeAtac3": "Flareon",
    "quick3": "Giro Fuego",
    "charge3": "Sofoco"
  },
  {
    "Tier": 2,
    "idRaid": 110,
    "RaidBoss": "Weezing",
    "BossCP": 12318,
    "Min CP": 1180,
    "MaxCP": 1247,
    "pokeAtac1": "Rhydon",
    "quick1": "Bofetón Lodo",
    "charge1": "Terremoto",
    "pokeAtac2": "Golem",
    "quick2": "Lanzarrocas",
    "charge2": "Roca Afilada",
    "pokeAtac3": "Alakazam",
    "quick3": "Confusión",
    "charge3": "Premonición"
  },
  {
    "Tier": 2,
    "idRaid": 125,
    "RaidBoss": "Electabuzz",
    "BossCP": 12390,
    "Min CP": 1188,
    "MaxCP": 1255,
    "pokeAtac1": "Rhydon",
    "quick1": "Bofetón Lodo",
    "charge1": "Terremoto",
    "pokeAtac2": "Donphan",
    "quick2": "Contraataque",
    "charge2": "Terremoto",
    "pokeAtac3": "Golem",
    "quick3": "Lanzarrocas",
    "charge3": "Roca Afilada"
  },
  {
    "Tier": 2,
    "idRaid": 126,
    "RaidBoss": "Magmar",
    "BossCP": 12718,
    "Min CP": 1220,
    "MaxCP": 1288,
    "pokeAtac1": "Rhydon",
    "quick1": "Bofetón Lodo",
    "charge1": "Terremoto",
    "pokeAtac2": "Golem",
    "quick2": "Lanzarrocas",
    "charge2": "Roca Afilada",
    "pokeAtac3": "Donphan",
    "quick3": "Contraataque",
    "charge3": "Terremoto"
  },
  {
    "Tier": 3,
    "idRaid": 59,
    "RaidBoss": "Arcanine",
    "BossCP": 17832,
    "Min CP": 1546,
    "MaxCP": 1622,
    "pokeAtac1": "Rhydon",
    "quick1": "Bofetón Lodo",
    "charge1": "Terremoto",
    "pokeAtac2": "Golem",
    "quick2": "Lanzarrocas",
    "charge2": "Roca Afilada",
    "pokeAtac3": "Donphan",
    "quick3": "Contraataque",
    "charge3": "Terremoto"
  },
  {
    "Tier": 3,
    "idRaid": 65,
    "RaidBoss": "Alakazam",
    "BossCP": 22646,
    "Min CP": 1569,
    "MaxCP": 1649,
    "pokeAtac1": "Tyranitar",
    "quick1": "Mordisco",
    "charge1": "Roca Afilada",
    "pokeAtac2": "Houndoom",
    "quick2": "Colmillo Ígneo",
    "charge2": "Llamarada",
    "pokeAtac3": "Scizor",
    "quick3": "Puño Bala",
    "charge3": "Cabeza de Hierro"
  },
  {
    "Tier": 3,
    "idRaid": 68,
    "RaidBoss": "Machamp",
    "BossCP": 18144,
    "Min CP": 1574,
    "MaxCP": 1650,
    "pokeAtac1": "Alakazam",
    "quick1": "Confusión",
    "charge1": "Premonición",
    "pokeAtac2": "Dragonite",
    "quick2": "Cola Dragón",
    "charge2": "Enfado",
    "pokeAtac3": "Charizard",
    "quick3": "Giro Fuego",
    "charge3": "Sofoco"
  },
  {
    "Tier": 3,
    "idRaid": 94,
    "RaidBoss": "Gengar",
    "BossCP": 19768,
    "Min CP": 1420,
    "MaxCP": 1496,
    "pokeAtac1": "Alakazam",
    "quick1": "Confusión",
    "charge1": "Premonición",
    "pokeAtac2": "Dragonite",
    "quick2": "Cola Dragón",
    "charge2": "Enfado",
    "pokeAtac3": "Tyranitar",
    "quick3": "Mordisco",
    "charge3": "Triturar"
  },
  {
    "Tier": 3,
    "idRaid": 134,
    "RaidBoss": "Vaporeon",
    "BossCP": 16696,
    "Min CP": 1724,
    "MaxCP": 1804,
    "pokeAtac1": "Exeggutor",
    "quick1": "Paranormal",
    "charge1": "Rayo Solar",
    "pokeAtac2": "Venusaur",
    "quick2": "Látigo Cepa",
    "charge2": "Rayo Solar",
    "pokeAtac3": "Victreebel",
    "quick3": "Ácido",
    "charge3": "Rayo Solar"
  },
  {
    "Tier": 3,
    "idRaid": 135,
    "RaidBoss": "Jolteon",
    "BossCP": 19883,
    "Min CP": 1484,
    "MaxCP": 1560,
    "pokeAtac1": "Rhydon",
    "quick1": "Bofetón Lodo",
    "charge1": "Terremoto",
    "pokeAtac2": "Donphan",
    "quick2": "Contraataque",
    "charge2": "Terremoto",
    "pokeAtac3": "Golem",
    "quick3": "Lanzarrocas",
    "charge3": "Roca Afilada"
  },
  {
    "Tier": 3,
    "idRaid": 136,
    "RaidBoss": "Flareon",
    "BossCP": 21155,
    "Min CP": 1581,
    "MaxCP": 1659,
    "pokeAtac1": "Golem",
    "quick1": "Lanzarrocas",
    "charge1": "Roca Afilada",
    "pokeAtac2": "Omastar",
    "quick2": "Pistola Agua",
    "charge2": "Hidrobomba",
    "pokeAtac3": "Tyranitar",
    "quick3": "Mordisco",
    "charge3": "Roca Afilada"
  },
  {
    "Tier": 4,
    "idRaid": 3,
    "RaidBoss": "Venusaur",
    "BossCP": 26921,
    "Min CP": 1395,
    "MaxCP": 1467,
    "pokeAtac1": "Charizard",
    "quick1": "Giro Fuego",
    "charge1": "Sofoco",
    "pokeAtac2": "Typhlosion",
    "quick2": "Ascuas",
    "charge2": "Sofoco",
    "pokeAtac3": "Espeon",
    "quick3": "Confusión",
    "charge3": "Premonición"
  },
  {
    "Tier": 4,
    "idRaid": 6,
    "RaidBoss": "Charizard",
    "BossCP": 28485,
    "Min CP": 1461,
    "MaxCP": 1535,
    "pokeAtac1": "Golem",
    "quick1": "Lanzarrocas",
    "charge1": "Roca Afilada",
    "pokeAtac2": "Omastar",
    "quick2": "Pistola Agua",
    "charge2": "Hidrobomba",
    "pokeAtac3": "Tyranitar",
    "quick3": "Mordisco",
    "charge3": "Roca Afilada"
  },
  {
    "Tier": 4,
    "idRaid": 9,
    "RaidBoss": "Blastoise",
    "BossCP": 24162,
    "Min CP": 1241,
    "MaxCP": 1309,
    "pokeAtac1": "Jolteon",
    "quick1": "Impactrueno",
    "charge1": "Rayo",
    "pokeAtac2": "Magneton",
    "quick2": "Chispa",
    "charge2": "Electrocañón",
    "pokeAtac3": "Venusaur",
    "quick3": "Látigo Cepa",
    "charge3": "Rayo Solar"
  },
  {
    "Tier": 4,
    "idRaid": 112,
    "RaidBoss": "Rhydon",
    "BossCP": 30512,
    "Min CP": 1804,
    "MaxCP": 1886,
    "pokeAtac1": "Venusaur",
    "quick1": "Látigo Cepa",
    "charge1": "Rayo Solar",
    "pokeAtac2": "Exeggutor",
    "quick2": "Paranormal",
    "charge2": "Rayo Solar",
    "pokeAtac3": "Vaporeon",
    "quick3": "Pistola Agua",
    "charge3": "Hidrobomba"
  },
  {
    "Tier": 4,
    "idRaid": 131,
    "RaidBoss": "Lapras",
    "BossCP": 21768,
    "Min CP": 1414,
    "MaxCP": 1487,
    "pokeAtac1": "Machamp",
    "quick1": "Contraataque",
    "charge1": "Puño Dinámico",
    "pokeAtac2": "Jolteon",
    "quick2": "Impactrueno",
    "charge2": "Rayo",
    "pokeAtac3": "Heracross",
    "quick3": "Contraataque",
    "charge3": "A Bocajarro"
  },
  {
    "Tier": 4,
    "idRaid": 143,
    "RaidBoss": "Snorlax",
    "BossCP": 25419,
    "Min CP": 1833,
    "MaxCP": 1917,
    "pokeAtac1": "Machamp",
    "quick1": "Contraataque",
    "charge1": "Puño Dinámico",
    "pokeAtac2": "Heracross",
    "quick2": "Contraataque",
    "charge2": "A Bocajarro",
    "pokeAtac3": "Tyranitar",
    "quick3": "Mordisco",
    "charge3": "Roca Afilada"
  },
  {
    "Tier": 4,
    "idRaid": 248,
    "RaidBoss": "Tyranitar",
    "BossCP": 34707,
    "Min CP": 2011,
    "MaxCP": 2097,
    "pokeAtac1": "Machamp",
    "quick1": "Contraataque",
    "charge1": "Puño Dinámico",
    "pokeAtac2": "Vaporeon",
    "quick2": "Pistola Agua",
    "charge2": "Hidrobomba",
    "pokeAtac3": "Heracross",
    "quick3": "Contraataque",
    "charge3": "A Bocajarro"
  }
];